import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="navbar-container">
        <nav className="navbar">
          <img />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about">About</a>
        </nav>
      </header>
      <main>
        <a href="">
        <div>
          <h2>Events in Haryana</h2>
          <p>Eu Lorem in nisi aute proident proident elit anim aute id aliquip laborum amet. Magna est eiusmod est Lorem eiusmod et proident esse laborum eu laborum laborum excepteur. Consectetur dolor ullamco veniam dolor eu duis duis veniam adipisicing minim mollit fugiat. </p>
        </div>
        </a>
      </main>
    </>
  );
}
